// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchrodingersBot;

#nullable disable

namespace SchrodingersBot.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20251107144334_v.1.1.0.1")]
    partial class v1101
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchrodingersBot.DB.DBO.AreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CenterLat")
                        .HasColumnType("float");

                    b.Property<double?>("CenterLon")
                        .HasColumnType("float");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("PolygonJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RadiusInMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxGameSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoginInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginInfoId");

                    b.ToTable("GameSubscriptions");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxLevelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxLoginInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Atoken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stoken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginInfos");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScreenshot")
                        .HasColumnType("bit");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxGameSubscriptionEntity", b =>
                {
                    b.HasOne("SchrodingersBot.DB.DBO.EncxLoginInfoEntity", "LoginInfo")
                        .WithMany()
                        .HasForeignKey("LoginInfoId");

                    b.Navigation("LoginInfo");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxLevelEntity", b =>
                {
                    b.HasOne("SchrodingersBot.DB.DBO.EncxGameSubscriptionEntity", "Game")
                        .WithMany("Levels")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxObjectEntity", b =>
                {
                    b.HasOne("SchrodingersBot.DB.DBO.EncxLevelEntity", "Level")
                        .WithMany("Objects")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxGameSubscriptionEntity", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("SchrodingersBot.DB.DBO.EncxLevelEntity", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
